---
  # fetch source code and install
- name: Clone source repository
  git:
    repo: "{{ repo_url }}"
    dest: /home/{{ ansible_ssh_user }}/{{ app_name }}
    version: "{{ git_branch }}"   # SHA-1 hash, the literal string HEAD, a branch name, or a tag name
    update: yes  # Does a git pull if the repo already exists
    force: yes
    accept_hostkey: yes
    key_file: /home/{{ ansible_ssh_user }}/.ssh/deploy_key
  become_user: "{{ ansible_ssh_user }}"

## SERVER ##
- name: Install virtualenv packages
  pip:
    requirements: /home/{{ ansible_ssh_user }}/{{ app_name }}/server/requirements.txt
    virtualenv: /home/{{ ansible_ssh_user }}/{{ app_name }}/server/env
    virtualenv_python: python3
  become_user: "{{ ansible_ssh_user }}"

- name: Install {{ app_name }} source
  pip:
    name: /home/{{ ansible_ssh_user }}/{{ app_name }}/server
    extra_args: '-e'   # installs editably
    virtualenv: /home/{{ ansible_ssh_user }}/{{ app_name }}/server/env
  become_user: "{{ ansible_ssh_user }}"

## CLIENT ##
- name: Remove existing build
  become: yes
  file:
    path: "{{ nginx_build_path }}"
    state: absent

- name: Run NPM install
  command: >
    npm install
  ignore_errors: yes
  args:
    chdir: /home/{{ ansible_ssh_user }}/{{ app_name }}/client

- name: Run NPM build
  command: >
    npm run build
  ignore_errors: yes
  args:
    chdir: /home/{{ ansible_ssh_user }}/{{ app_name }}/client

- name: Move new build directory into place
  become: yes
  command: >
    mv build "{{ nginx_build_path }}"
  args:
    chdir: /home/{{ ansible_ssh_user }}/{{ app_name }}/client

- name: Ensure build directory has appropriate permissions
  become: yes
  file:
    path: "{{ nginx_build_path }}"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Ensure build directory is actually present
  stat: 
    path: "{{ nginx_build_path }}"
  register: file_details

- fail:
    msg: The NPM build directory is missing from "{{ nginx_build_path }}"
  when: file_details.stat.isdir == false

## RICK ROLL ##
# - name: Copy index.html to html
#   become: true
#   copy:
#     src: files/index.html
#     dest: /usr/share/nginx/html/index.html
#     force: yes

# - name: Copy media to html
#   become: true
#   copy:
#     src: files/video.mp4
#     dest: /usr/share/nginx/html/video.mp4
#     force: yes
