---
# set up nginx service, enable, and restart
- name: Template systemd gunicorn config
  template:
    src: templates/gunicorn.j2
    dest: /etc/systemd/system/gunicorn.service
    force: yes

- name: Start systemd app service
  systemd:
    name: gunicorn.service
    state: restarted
    enabled: yes

- name: Template nginx global config
  template:
    src: templates/nginx.j2
    dest: /etc/nginx/nginx.conf
    force: yes

- name: Template nginx site config
  template:
    src: templates/site.j2
    dest: /etc/nginx/conf.d/{{ app_name }}.conf
    force: yes

- name: Add robots.txt for SEO & Indexing
  become: true
  copy:
    src: files/robots.txt
    dest: "{{ nginx_build_path }}/robots.txt"
    force: yes

- name: Add robocop.txt for Shits & Giggles
  become: true
  copy:
    src: files/robocop.txt
    dest: "{{ nginx_build_path }}/robocop.txt"
    force: yes

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Open firewall
  ufw:
    rule: allow
    name: Nginx Full
